---
title: "年中工作总结"
subtitle: "Mid-Year Work Summary"
author: "陈琼"
date: 2024-7-10
date-format: "dddd MMM D, YYYY"
format:
  canhosp-revealjs:
    slide-number: false
    scrollable: false
    sc-sb-title: h1
    footer: "Don’t let yesterday take up too much of today."
    address: "ZhengZhou"
revealjs-plugins:
  - attribution
filters:
   - roughnotation
   - reveal-header
   - reveal-auto-agenda
auto-agenda:
  bullets: numbered
  heading: 主要内容
slide-level: 2
title-slide-style: pandoc
title-slide-attributes:
  data-background-color: "lightblue"
  data-background-size: 100%, cover
  background-opacity: 0.3
---

# 以人群为基础的肿瘤登记

## 完成工作内容{.smaller}

> 完成常规工作内容是做好其他工作的前提和基础

1. 完成《河南省肿瘤登记实施方案》，卫健委审核中
1. 网络直报信息管理系统的升级和维护
1. 2021年肿瘤登记数据质量控制审核报告
1. 部分登记处的现场督导和质量控制
1. 国家肿瘤登记处下达的其他任务

## 工作产出情况{.smaller}

#### 书籍

1. 撰写《2023河南省肿瘤登记年报》
1. 肿瘤登记数据的逻辑审核


#### 论文

1. Childhood cancer incidence, mortality, and 5-year survival in Henan, China
1. An R package（crcheck） for internal consistency check in population based cancer registration
1. IARC meeting (R package for data analysis in cancer registration)

## 成绩与荣誉

1. 省级单位杰出贡献奖
1. 肿瘤登记杰出贡献奖(13)
1. 肿瘤登记工作优秀奖(12)
1. 肿瘤登记工作进步奖(8)
1. 五大洲发病率第十二卷贡献奖(16)
1. 全国肿瘤登记工作先进个人(12)

## 下半年计划

1. 发布《2023河南省肿瘤登记年报》
1. 发布河南省肿瘤登记实施方案
1. 河南省肿瘤登记专业人员综合能力提升培训项目
1. 编写《基于R语言的肿瘤登记数据分析与利用》
1. 全国肿瘤登记培训教材编制工作
  - 内部一致性数据逻辑审核手册
  - 骨肿瘤、脑肿瘤的编码

# 癌症一级预防

## 完成工作内容

- 启动癌症一级预防危险因素调查项目首次随访工作
- 签署癌症预防控制体系建设推广（医防结合）项目


## 下半年计划

- 撰写癌症预防控制体系建设推广（医防结合）项目方案
- 数据分析及论文撰写


# 科研工作

## 进展情况

- Lifetime Risk of Developing and Dying from Cancer in Henan, China’:’ Current Status, Temopral Trends, and Disparities，JNCC 修稿中
- Global, regional, and national lifetime risk of lung cancer，撰写中
- 全球肺癌终生患癌和死亡风险情况分析，中国肿瘤
  
## 下半年计划

- Temporal trends on lifetime risk of esophageal cancer in high-risk areas in China.
- Evaluation of the effectiveness of the AMP Model in adjusting for multiple primary cancers in estimating Lifetime cancer risk.
- PYLL due to cancer adjusting for main risk factors

# 其它工作

## 工作内容

- 参与市县级癌症中心评审工作


# 谢谢大家 {.no-auto-agenda}

> Find a job you enjoy doing, and you will never have to work a day in your life. ― Mark Twain

::: footer
个人网站：[普癌新声https://www.chenq.site](https://chenq.site)
:::
