project:
  type: website
website:
  title: "普癌新声"
  description: "一个公共卫生医师的个人网站"
  twitter-card: true
  open-graph: true
  site-url: https://slides.chenq.site

  navbar:
    background: primary
    search: true
    left:
      - icon: house
        href: index.qmd
        text: Home
      - icon: tropical-storm
        href: https://chenq.site/qsight
        text: Qsight博客
      - icon: pen
        href: https://diary.chenq.site
        text: 随笔录
      - icon: hexagon
        href: https://gigu003.github.io/canregtools
        text: Packages
      - icon: journal-medical
        href: https://chenq.site/publications
        text: 出版作品
      - href: https://chenq.site/about.html
        text: 关于

  page-footer:
    border: true
    left: "Copyright@Qiong Chen"
    center: "豫ICP备2021032022号"
    right:
      - icon: github
        href: https://github.com/gigu003
        aria-label: Qiong@GitHub
      - icon: rss
        href: /index.xml
        aria-label: RSS     
freeze: auto
format:
  html:
    theme: [flatly, custom.scss]
